### ISSUE TITLE
Spike artifacts when zoomed out over GeoJSON datasource

### ISSUE THREAD

**Issue by harrycollin** [heremaps/harp.gl#1460] opened 2020-04-15 18:42 UTC
When zoomed out over the attached GeoJSON data source there are spike-like artifacts everywhere. 

To reproduce:

1. Load GeoJSON data source onto then map.
2. Zoom out high over the data source.

![image](https://user-images.githubusercontent.com/10602138/79375399-78dbbf80-7f50-11ea-8816-0658e827b5c9.png)

 - OS: Windows 10 (64-bit)
 - Browser: Brave Browser - Version 1.5.123 Chromium: 80.0.3987.163 (Official Build) (64-bit)
 - Version: 0.14

Here is the geojson.
[countours.zip](https://github.com/heremaps/harp.gl/files/4483110/countours.zip)

Here is the style used.
[style.txt](https://github.com/heremaps/harp.gl/files/4483146/style.txt)

**Comment by ninok** [comment] 2020-04-15 18:45
Thanks for creating the issue. Can you please also attach the style that you used for the geojson?

**Comment by HHammerite** [comment] 2020-04-15 18:48
@ninok Updated the original

**Comment by HHammerite** [comment] 2020-04-15 18:50
@ninok Where you see 'this.fillColor.hex' & 'this.strokeColor.hex' it is just a random hex colour for the moment.

**Comment by ninok** [comment] 2020-04-16 18:19
Still cannot reproduce on Chrome 81 Ubuntu 20.04.
@HHammerite Can you try to load your file in this example: https://www.harp.gl/docs/master/examples/#geojson-viewer.html

**Comment by HHammerite** [comment] 2020-04-16 18:39
Interesting. I can't reproduce it either on that example. Here is a screenshot of me zoomed out at a similar distance. 
![image](https://user-images.githubusercontent.com/10602138/79493578-9759bd80-8019-11ea-843e-838743d26368.png)

I do see it when zoomed in a bit more.
![image](https://user-images.githubusercontent.com/10602138/79493699-c40dd500-8019-11ea-9ad6-640b5b2c03a0.png)

But when zoomed, even more, the whole layer disappears. 
![image](https://user-images.githubusercontent.com/10602138/79493836-f3244680-8019-11ea-9e6b-996924baa1af.png)

I think I might record a video and post it here because the experience is so inconsistent.

**Comment by HHammerite** [comment] 2020-04-16 21:10
Here is a video I recorded https://www.youtube.com/watch?v=5E9MdB9JHjc

**Comment by nzjony** [comment] 2020-06-22 10:35
Removing the wontfix label, it seems to be a genuine problem. Could be related to the issue reported internally: HARP-10866

**Comment by nzjony** [comment] 2020-09-07 11:46
This is still a valid issue. I managed to recreate it, so will reopen.

**Comment by harrycollin** [comment] 2020-09-07 12:06
@nzjony Awesome! Are there any initial thoughts on what could be causing this?

**Comment by nzjony** [comment] 2020-09-07 12:15
@harrycollin , basically we don't handle rendering `MultiPolygon`'s correctly when styled using `solid-line`.

It seems it is an issue with the way we use geojson-vt to do the subdivision, we need to know if the edge added is part of the original data or whether it is synthentic. 

@robertoraggi created the internal ticket and can perhaps give some more info than I can describe.

**Comment by harrycollin** [comment] 2020-09-07 12:18
@nzjony thanks for the insight. I look forward to hearing more on this :)

**Comment by nzjony** [comment] 2020-09-07 12:23
@harrycollin , no worries. All going well, we plan to start fixing it in 1-2 weeks.

**Comment by nzjony** [comment] 2020-11-10 10:35
@harrycollin , sorry no update on our side.

**Comment by harrycollin** [comment] 2020-11-10 11:00
No problem!

**Closed** 2021-06-18 23:31 UTC
Labels: HARP-11233, wontfix
