### ISSUE TITLE
The map doesn't fit with the earth

### ISSUE THREAD

**Issue by PrUnSt** [heremaps/harp.gl#1558] opened 2020-05-26 02:22 UTC
**To Reproduce**
1. Go to 'getting-started_globe-projection.html'
2. Scroll down
3. See error

![1](https://user-images.githubusercontent.com/30542005/82854351-c594bc00-9f3a-11ea-86ac-f702f69e82cf.png)

**Comment by nzjony** [comment] 2020-05-26 05:55
hi @PrUnSt , thanks for your issue. I tried to reproduce here: https://www.harp.gl/docs/master/examples/#getting-started_globe-projection.html but I wasn't able to. 

What do you mean by "Scroll down"? Do you mean to zoom out?

**Comment by nzjony** [comment] 2020-05-26 07:24
@PrUnSt , I just had a thought, this happens when zooming in? Then it resolves itself correct?

**Comment by PrUnSt** [comment] 2020-05-27 02:22
Maybe it was caused by network，I see many requests fail, can I publish the map service myself？

**Comment by nzjony** [comment] 2020-05-27 06:24
@PrUnSt , I could reproduce it. Do you think this could be a duplicate of: https://github.com/heremaps/harp.gl/issues/1384 ?

**Comment by PrUnSt** [comment] 2020-05-27 09:24
yes

**Comment by nzjony** [comment] 2020-05-27 11:15
Ok, cool, I will close this issue and link the other one to this saying that it has been reported again.

**Closed by nzjony** 2020-05-27 11:15 UTC
