### ISSUE TITLE
 Customize the texture of the extrudePolygon or extrudebuilding

### ISSUE THREAD

**Issue by datouzhan** [heremaps/harp.gl#1854] opened 2020-09-19 08:43 UTC
**Is your feature request related to a problem? Please describe.**
Will Harpgl support custom top and side texture maps for extrudePolygon?

**Describe the solution you'd like**
 i try to change texture maps for extrudePolygon,but it fail.like this，it  covers the entire extrudePolygon

![image](https://user-images.githubusercontent.com/20176393/93662957-a7793b80-fa96-11ea-9780-5dc471600f07.png)
What I want to achieve is to set the side and top textures separately，like this:
![image](https://user-images.githubusercontent.com/20176393/93663020-31290900-fa97-11ea-915b-b0a345611162.png)

**Comment by nzjony** [comment] 2020-09-21 06:14
@datouzhan , thanks for your bug report.

We will need to have a new `textureCoordinateType`, which works with 3D buildings. I will create an internal ticket and discuss with the team.

**Comment by datouzhan** [comment] 2020-09-21 06:35
Thank you very much and i hope to hear the good news. And then, if there will be a terrain example?Because the api provides TerrainTechnique And Terrain style, but I don’t know what type of data is needed to show the terrain.

**Comment by nzjony** [comment] 2020-09-21 07:28
@datouzhan , just so I understand your needs correctly. You want to put some windows etc on the buildings?

There will be some artifacts at the boundary of tiles where buildings are cut. Is that acceptable? I.e. the texturing will be applied in this case twice, which may be undesirable.

**Comment by datouzhan** [comment] 2020-09-21 07:42
i  want to change the texture map on the top and side for the 3dbuilding.I don't think it has much impact.i can accept it.

**Comment by datouzhan** [comment] 2020-09-21 07:47
By the way, how the terrain should be used. The api document provide the TerrainTechnique And Terrain style,But didn't tell me what data to use and how to apply it.

**Comment by nzjony** [comment] 2020-09-21 08:04
@datouzhan , we have some terrain examples but they are only internally, because they use some internal services which are not yet production ready.

Maybe we can generate some simple demo which shows terrain using some randomly generated noise. I will ask internally if we can do something like that in the upcoming sprints.

**Comment by datouzhan** [comment] 2020-09-21 08:10
I'm looking forward to hearing your good news.

**Comment by datouzhan** [comment] 2020-09-21 08:18
I encountered some problems in the process of verifying shader.  For example, to realize the dynamic flow of water surface.I tried to pass in pictures, textures and other dynamic parameters, but failed.
![{T8R4PYNTKU~H U0%CHW82K](https://user-images.githubusercontent.com/20176393/93745316-e38ed680-fc25-11ea-9e0a-6ecdea673f74.png)
![`IITH$6XVGH)@L79M_C%`Z4](https://user-images.githubusercontent.com/20176393/93745353-f43f4c80-fc25-11ea-8ade-2d2aac32f3b6.png)
Can you answer it for me?

**Comment by nzjony** [comment] 2020-09-21 09:07
@datouzhan , I spoke with @robertoraggi, it seems there is some issue transferring the texture to the WebWorker, when you create the `MapView`, can you try and please add this option:

`decoder: new VectorTileDecoder()`

And let me know what error you get?

**Comment by nzjony** [comment] 2020-09-21 09:36
@datouzhan , I spoke a bit more with @robertoraggi .

Here is an example uploading a texture: https://www.harp.gl/docs/master/examples/#styling_textured-areas.html

And here is the example using a custom shader: https://www.harp.gl/docs/master/examples/#datasource_geojson_custom-shader.html

We just need to make a task internally to create an example which using a custom texture in a custom shader. We looked at the code, but it isn't fully clear if this is supported, or not. At least there is quite a bit of hard coded properties that need to be looked at to see if they are doing what they should.

I will create a task and hopefully we can help you soon.

**Comment by datouzhan** [comment] 2020-09-21 09:45
Yes, I am the reference example of using a custom shader.The example only defines that the color is passed by the test.And I tried to pass in the texture map but failed.Thank you very much for your support.I will be looking forward to hearing your good news. i will add this option:decoder: new VectorTileDecoder() to try it.

**Comment by datouzhan** [comment] 2020-09-21 09:50
Because in addition to texturing, I also need to make the water flow. So I need to use custom shaders to achieve dynamic water flow like an ocean example  to threejs.

**Comment by nzjony** [comment] 2020-09-21 10:21
Sounds very cool what you are trying to achieve @datouzhan ! Hopefully we can prioritise this internally so we can help you out. I will keep you posted.

**Comment by datouzhan** [comment] 2020-09-21 10:25
Thank you very much for your support.if i can achieve this scene,it will be very cool.

**Comment by datouzhan** [comment] 2020-09-24 03:33
hi , @nzjony ,i try to use the custom shader to achieve thre custom shader,but it has some problem. I have no problem implementing it in a separate example of threejs,like this:
![image](https://user-images.githubusercontent.com/20176393/94097411-09e88800-fe59-11ea-94a7-f4ba096ec3f9.png)
but when i want to achieve it in harpgl ,it has some problem ,like this:
![image](https://user-images.githubusercontent.com/20176393/94097498-2edcfb00-fe59-11ea-9694-4d541e3465a7.png)
When I rotated an angle, the color of the water changed.like this:
![image](https://user-images.githubusercontent.com/20176393/94097596-5df36c80-fe59-11ea-9abe-a68b3070d744.png)
can u answer it for me, i don't know how to solve it.
![image](https://user-images.githubusercontent.com/20176393/94097685-8da27480-fe59-11ea-837e-a6cc827037ca.png)
And When I pull closer to the angle, the object will keep shaking.But if it is added to the map in the way of vector tiles, there will not be such a problem.

**Comment by nzjony** [comment] 2020-09-24 11:43
@datouzhan , very awesome progress!

Do you have the demo available somewhere for me to test locally?

**Comment by datouzhan** [comment] 2020-09-27 03:04
I have a demo to send you. Shall I send it to you in the form of mailbox or how to send it to you?

**Comment by datouzhan** [comment] 2020-09-28 07:26
hi @nzjony ,I created an online test example. https://codepen.io/datouzhan/pen/XWdQNmR?__cf_chl_jschl_tk__=de4ce1912ff7736d24e028040e2dc7e74b6cb78b-1601274687-0-AZkpQgugaAb_HzGFRxXBAzBp_DcyjtiaPEA1KPzgXWtOAZAxNUBULmXfiKMZZy6puG2ldQ9c_fAnFFTRQZM23_spNHDkObOUm_A2JeU7xWLLVAtMfmqQrOiP-lm2a2Tc2ocm19NI9DFh3V_kPff9MRw-rxToU7n6YYpze1eqdRkP1lN5drKMsFeNYu-s23RUHbQRH4MbZK_LS29GlEng3UHSb6UJVQJn90OurMwkNMJbgr5fqs29jVU-wd9hqn881yz3nWA5G93AAt7duI_ULmFsFRhvJ-dlD6-KopBil5jgZerGgXVFhOB0_tdviyC4MPiSddH_DC50HWYTTNWpvFWwJmcd22JjS8Ez8LH_07kh

**Comment by nzjony** [comment] 2020-10-02 09:32
@datouzhan , cool demo, yes I can open it.

I think the problem is the normals for the texture: techbrood.com/threejs/examples/textures/waternormals.jpg

In harp.gl, we use a slightly different use of the coordinates, we use x to describe the longitude, y to describe the latitude, and z to describe the height. So basically, compared to a normal 3d engine which uses the x&z plane to move horizontally, and the y to move vertically, we swap the z and y. And my guess is that the normals in the texture assume that.

Actually, I just looked at the shader code in three.js for the water, and it seems that the z and y are flipped in the shader:

`vec3 surfaceNormal = normalize( noise.xzy * vec3( 1.5, 1.0, 1.5 ) );'`

Maybe try a local build of three.js with that modified and see if it fixes the issue?

**Comment by datouzhan** [comment] 2020-10-09 07:06
yes,it fixes the issue, thank you very much.You helped me a lot.
![image](https://user-images.githubusercontent.com/20176393/95552429-47473b00-0a3f-11eb-93fc-20b8e9c020a0.png)
But when I use the scroll wheel to move slowly, the scene will shake,can you answer it for me? This phenomenon only occurs on the additional threejs objects.
![Uploading shake.gif…]()
![Uploading shake2.gif…]()

**Comment by datouzhan** [comment] 2020-10-09 07:11
yes,it fixes the issue, thank you very much.You helped me a lot.
![image](https://user-images.githubusercontent.com/20176393/95553535-5929dd80-0a41-11eb-8e5b-e0f978d1cce2.png)
But when I use the scroll wheel to move slowly, the scene will shake,can you answer it for me? This phenomenon only occurs on the additional threejs objects.
![shake](https://user-images.githubusercontent.com/20176393/95553162-90e45580-0a40-11eb-853f-e1de93b1b7e7.gif)

**Comment by Astrak** [comment] 2020-10-22 12:27
Very beautiful, looking forward to it!

 @nzjony how far is the team from delivering terrain? Will it work with all the other existing features? Will the shading of the globe atmosphere on the ground also adapt to the terrain's height? Thanks

**Comment by nzjony** [comment] 2020-10-22 14:47
@Astrak , yeah, @datouzhan  has made some cool demo!

Terrain requires some changes to the platform to be able to serve such tiles, I don't know how far we are away from this just yet, and I think it isn't such a high priority just yet. The terrain shading would also be blocked by that.

**Closed** 2021-01-09 15:02 UTC
Labels: HARP-12098, HARP-12101, wontfix

**Comment by d3vilsn0w** [comment] 2022-03-19 22:19
Is it possible to share an example adding a shader to the water layer?
