### ISSUE TITLE
load 3D object issue

### ISSUE THREAD

**Issue by MalekBEKRI97** [heremaps/harp.gl#2246] opened 2021-07-25 16:16 UTC
i tried to load on click the cube like what i found in the documentation but the texture was not clear 
![Capture](https://user-images.githubusercontent.com/65353353/126905987-bc16fa81-98cd-4cfb-9e1c-70811519df91.PNG)

**Comment by nzjony** [comment] 2021-07-25 20:13
@MalekBEKRI97 , thanks for creating an issue!

Do you mean the texture can't be seen, even though you applied it to the cube?

Do you have some demo / code snippet I can try?

**Comment by MalekBEKRI97** [comment] 2021-07-25 23:34
Yes, even i Added the cube on click it doesn’t show the texture , i’ll send you the hole test project it’s similar to the tutorial documentation , and thank you in advance

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by MalekBEKRI97** [comment] 2021-07-25 23:45
[harp-map.zip](https://github.com/heremaps/harp.gl/files/6874719/harp-map.zip)

**Comment by nzjony** [comment] 2021-07-26 06:52
@MalekBEKRI97 

I tried your example, I see the code that adds the cube:

```
 canvas.onclick = evt => {
   //Create the three.js cube
   const geometry = new THREE.BoxGeometry(100, 100, 100);
   const material = new THREE.MeshStandardMaterial({ color: 0x00ff00fe });
   const cube = new THREE.Mesh(geometry, material);
   cube.renderOrder = 100000;

   //Get the position of the click
   const geoPosition = map.getGeoCoordinatesAt(evt.pageX, evt.pageY);
   cube.geoPosition = geoPosition;

   //Add object to the map
   map.mapAnchors.add(cube);
   map.update();
} 
```

But I don't see any code which adds a texture to the cube.

Are you referring to textures on the cube or on the buildings?

**Comment by MalekBEKRI97** [comment] 2021-07-26 11:20
i mean the color of the cube for example "const material = new THREE.MeshStandardMaterial({ color: 0x00ff00fe })" it's not visible in the all sides

**Comment by MalekBEKRI97** [comment] 2021-07-26 11:22
![Capture](https://user-images.githubusercontent.com/65353353/126980874-a83a59f2-1dbe-4763-b0f9-c1c7bd4fd084.PNG)

**Comment by nzjony** [comment] 2021-07-26 11:42
thanks @MalekBEKRI97 

Yes, I can reproduce, I tried removing the code that adds all {{fbx|obj}} files, but keep the code to place the boxes and they are rendered correctly, i.e. without the models, I get the cubes looking solid pink, quite strange!

It seems something weird goes on when loading the models. I don't quite know what the problem is... I would have to look further but I don't have the time to look now sorry. Perhaps you can take a look?

**Comment by MalekBEKRI97** [comment] 2021-07-26 11:45
yes thank you , i will try again and look for other solutions and thank you again or your time

**Comment by nzjony** [comment] 2021-07-26 11:45
One think you can look at is what lights are in the scene? Maybe there are too many being added?

**Comment by nzjony** [comment] 2021-07-26 11:55
@MalekBEKRI97 , I read that fbx can export lights. Best fix your models to not contain any lights.

**Comment by MalekBEKRI97** [comment] 2021-07-26 11:59
i tried now to add some materiel and wireframe to the fbx , and i get a better view , and also while moving around i see the lights like you said 
![Capture](https://user-images.githubusercontent.com/65353353/126985202-39634e0f-a2c3-4b5b-a7ae-48999a97ee5b.PNG)

**Comment by nzjony** [comment] 2021-08-03 14:05
@MalekBEKRI97 , is there anything that I can help you with? Did you find the solution?

**Comment by nzjony** [comment] 2021-09-28 14:32
@MalekBEKRI97 , will close this issue, and please re-open if you need further help.

**Closed by nzjony** 2021-09-28 14:32 UTC
